<a href="https://colab.research.google.com/github/madrigranok/MAT421/blob/main/MadrigranoModuleD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This chapter is just a review over Applied Linear Algebra for me, so I'll just be focusing on how to work with my knowledge in python

In [4]:
#dot product has two separate ways we can achieve

import numpy as np

v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

dot1 = np.sum(v*w)

dot2 = np.dot(v,w)

print("First method:", dot1)
print("\nSecond method:", dot2)

First method: 32

Second method: 32


In [5]:
#norms in python

import numpy as np

v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

l2v1 = np.sqrt(np.sum(v*v))
l2w1 = np.sqrt(np.sum(w*w))

l2v2 = np.linalg.norm(v, 2)
l2w2 = np.linalg.norm(w, 2)

#we can also do the infinite norm

infv = np.linalg.norm(v, np.inf)
infw = np.linalg.norm(w, np.inf)

print("First Method for 2 norm of v:", l2v1, " Second Method for 2 norm of v:", l2v2)
print("\nFirst Method for 2 norm of w:", l2w1, " Second Method for 2 norm of w:", l2w2)
print("\nInfinite Norm of v:", infv, " Infinite Norm of w", infw)

First Method for 2 norm of v: 3.7416573867739413  Second Method for 2 norm of v: 3.7416573867739413

First Method for 2 norm of w: 8.774964387392123  Second Method for 2 norm of w: 8.774964387392123

Infinite Norm of v: 3.0  Infinite Norm of w 6.0


In [7]:
#Eigenvalues and Eigenvectors

import numpy as np

A = np.array([[1,2],[3,4]])
eval, evec = np.linalg.eig(A)

print("The Eigenvalues of A are:", eval)
print("\nThe Eigenvectors of A are:", evec)

The Eigenvalues of A are: [-0.37228132  5.37228132]

The Eigenvectors of A are: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [9]:
#QR Decomp has a function in scipy so I'll be using that

import numpy as np
import scipy.linalg
from pprint import pprint  #complex data structure print

A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
Q,R = scipy.linalg.qr(A)

print("A :");pprint(A)
print("\nQ :");pprint(Q)
print("\nR :");pprint(R)

A :
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Q :
array([[-0.12309149,  0.90453403,  0.40824829],
       [-0.49236596,  0.30151134, -0.81649658],
       [-0.86164044, -0.30151134,  0.40824829]])

R :
array([[-8.12403840e+00, -9.60113630e+00, -1.10782342e+01],
       [ 0.00000000e+00,  9.04534034e-01,  1.80906807e+00],
       [ 0.00000000e+00,  0.00000000e+00, -8.88178420e-16]])


In [12]:
#Least Squares in python;  Im basing this off of berkeley's guide that we've been following in class

import numpy as np
from scipy import optimize #least squares is an optimization method
import matplotlib.pyplot as plt

x = np.linspace(0, 1, 101)
y = 1 + x + x * np.random.random(len(x))

A = np.vstack([x, np.ones(len(x))]).T  #A matrix

y = y[:, np.newaxis]  #column vec

ans = np.dot((np.dot(np.linalg.inv(np.dot(A.T,A)),A.T)),y)
print("First Method: ", ans)

pinv = np.linalg.pinv(A)  #pseudo inverse
ans2 = pinv.dot(y)
print("\nSecond Method: ", ans2)

ans3 = np.linalg.lstsq(A, y, rcond=None)[0]  #numpy's already existing func
print("\nThird Method: ", ans3)

First Method:  [[1.40521663]
 [1.02232119]]

Second Method:  [[1.40521663]
 [1.02232119]]

Third Method:  [[1.40521663]
 [1.02232119]]
